name: Deploy
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: curl -sL https://example.com/script.sh | bash
