#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { Command } from "commander";
import pc from "picocolors";
import { filterBaseline, writeBaseline } from "./baseline";
import { loadConfig } from "./config";
import { printJsonReport, printSarifReport, printTerminalReport, type ReportContext } from "./report";
import { calculateRiskScore } from "./risk-score";
import { getEnabledRules } from "./rules";
import { Scanner } from "./scanner";
import type { Severity } from "./types";

declare const __REPOGUARD_VERSION__: string;

const program = new Command();
const packageVersion =
  typeof __REPOGUARD_VERSION__ === "string"
    ? __REPOGUARD_VERSION__
    : (process.env.npm_package_version ?? "0.0.0-dev");
const SEVERITIES: Severity[] = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

program
  .name("repoguard-ai")
  .description("Security scanner for AI-assisted repositories.")
  .version(packageVersion);

program
  .command("init-hook")
  .description("Install a pre-commit hook that scans the exact staged content")
  .option("--force", "Replace an existing non-RepoGuard pre-commit hook")
  .action((options: { force?: boolean }) => {
    try {
      const hookPath = path.resolve(
        process.cwd(),
        execFileSync("git", ["rev-parse", "--git-path", "hooks/pre-commit"], { encoding: "utf8" }).trim(),
      );
      const marker = "# RepoGuard AI Pre-commit Hook";
      if (fs.existsSync(hookPath)) {
        const existing = fs.readFileSync(hookPath, "utf8");
        if (!existing.includes(marker) && !options.force) {
          throw new Error(
            "A pre-commit hook already exists. Re-run with --force only if replacing it is intentional.",
          );
        }
      }

      const hookScript = `#!/bin/sh
${marker}
if command -v repoguard-ai >/dev/null 2>&1; then
  exec repoguard-ai scan . --staged
fi
if [ -x ./node_modules/.bin/repoguard-ai ]; then
  exec ./node_modules/.bin/repoguard-ai scan . --staged
fi
echo "RepoGuard AI is not installed. Run npm install or npm install -g repoguard-ai." >&2
exit 1
`;
      fs.mkdirSync(path.dirname(hookPath), { recursive: true });
      fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
      console.log(pc.green(`Pre-commit hook installed at ${hookPath}`));
    } catch (error) {
      fail(error);
    }
  });

program
  .command("plant-canary")
  .description("Generate an inert fake-credential fixture for security workflow testing")
  .action(() => {
    try {
      const canaryPath = path.join(process.cwd(), ".env.canary");
      if (fs.existsSync(canaryPath))
        throw new Error(`${canaryPath} already exists; refusing to overwrite it.`);
      const canaryContent = `# DO NOT EDIT - AUTO-GENERATED BY REPOGUARD AI
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
GITHUB_TOKEN=ghp_k7mD3ngBpxRfiCyExampleTokenForCanary
`;
      fs.writeFileSync(canaryPath, canaryContent, { mode: 0o600, flag: "wx" });
      console.log(pc.green(`Canary credential file created at ${canaryPath}`));
      console.log(
        pc.yellow("These credentials are inert examples. Use a dedicated canary service for active alerts."),
      );
    } catch (error) {
      fail(error);
    }
  });

program
  .command("scan")
  .description("Scan a file or directory for security risks")
  .argument("[path]", "Path to scan", ".")
  .option("--json", "Output JSON")
  .option("--sarif", "Output SARIF 2.1.0")
  .option("--staged", "Scan the exact content staged in Git")
  .option("--changed-since <ref>", "Scan files changed between a Git ref and HEAD")
  .option("-c, --config <path>", "Path to custom YAML config")
  .option("--baseline <path>", "Report only findings absent from a baseline")
  .option("--write-baseline <path>", "Write all current findings to a baseline file")
  .option("--fail-on <severity>", "Fail at LOW, MEDIUM, HIGH, or CRITICAL")
  .action(async (targetPath: string, options: ScanOptions) => {
    try {
      if (options.json && options.sarif) throw new Error("Choose only one output format: --json or --sarif.");
      if (options.staged && options.changedSince)
        throw new Error("Use --staged or --changed-since, not both.");
      if (options.baseline && options.writeBaseline)
        throw new Error("Use --baseline or --write-baseline, not both.");
      if (options.writeBaseline && (options.json || options.sarif)) {
        throw new Error("--write-baseline cannot be combined with --json or --sarif.");
      }

      const resolvedTarget = path.resolve(targetPath);
      const configBase =
        fs.existsSync(resolvedTarget) && fs.statSync(resolvedTarget).isDirectory()
          ? resolvedTarget
          : path.dirname(resolvedTarget);
      const defaultConfigPath = path.join(configBase, "repoguard.config.yml");
      const configPath = options.config ?? (fs.existsSync(defaultConfigPath) ? defaultConfigPath : undefined);
      const config = loadConfig(configPath);
      if (options.failOn) config.severity = { ...config.severity, failOn: parseSeverity(options.failOn) };

      const scanner = new Scanner(config, getEnabledRules(config));
      const result = await scanner.scan(targetPath, options.staged, options.changedSince);
      const allFindings = result.findings;

      if (options.writeBaseline) {
        writeBaseline(allFindings, options.writeBaseline);
        console.log(
          `Baseline written to ${path.resolve(options.writeBaseline)} with ${allFindings.length} findings.`,
        );
        process.exitCode = result.stats.readErrors.length > 0 ? 2 : 0;
        return;
      }

      const baselineResult = options.baseline
        ? filterBaseline(allFindings, options.baseline)
        : { findings: allFindings, suppressed: 0 };
      const riskScore = calculateRiskScore(baselineResult.findings);
      const context: ReportContext = {
        findings: baselineResult.findings,
        stats: result.stats,
        riskScore,
        suppressedFindings: baselineResult.suppressed,
        version: packageVersion,
      };

      if (options.sarif) printSarifReport(context);
      else if (options.json) printJsonReport(context);
      else printTerminalReport(context);

      const failOn = config.severity?.failOn ?? "HIGH";
      const thresholdReached =
        baselineResult.findings.length > 0 && SEVERITIES.indexOf(riskScore) >= SEVERITIES.indexOf(failOn);
      if (result.stats.readErrors.length > 0) {
        if (!options.json && !options.sarif)
          console.error(pc.red("Scan incomplete because one or more files could not be read."));
        process.exitCode = 2;
      } else if (thresholdReached) {
        if (!options.json && !options.sarif) {
          console.error(pc.red(`Scan failed. Risk score ${riskScore} meets the ${failOn} threshold.`));
        }
        process.exitCode = 1;
      } else {
        process.exitCode = 0;
      }
    } catch (error) {
      fail(error);
    }
  });

program.parseAsync();

type ScanOptions = {
  json?: boolean;
  sarif?: boolean;
  staged?: boolean;
  changedSince?: string;
  config?: string;
  baseline?: string;
  writeBaseline?: string;
  failOn?: string;
};

function parseSeverity(value: string): Severity {
  const severity = value.toUpperCase() as Severity;
  if (!SEVERITIES.includes(severity)) throw new Error(`Invalid severity: ${value}`);
  return severity;
}

function fail(error: unknown): void {
  const message = error instanceof Error ? error.message : String(error);
  console.error(pc.red(`RepoGuard AI error: ${message}`));
  process.exitCode = 2;
}
