#!/usr/bin/env node
import { Command } from "commander";
import { loadConfig } from "./config";
import { Scanner } from "./scanner";
import { getEnabledRules } from "./rules";
import { printTerminalReport, printJsonReport, printSarifReport } from "./report";
import { calculateRiskScore } from "./risk-score";
import { Severity } from "./types";
import pc from "picocolors";
import * as fs from "fs";
import * as path from "path";

const program = new Command();

program
  .name("repoguard-ai")
  .description("Security scanner for AI-assisted repositories.")
  .version("0.1.0");

program
  .command("init-hook")
  .description("Installs a pre-commit hook to prevent committing leaked secrets")
  .action(() => {
    try {
      const hookPath = path.join(process.cwd(), ".git", "hooks", "pre-commit");
      const hookScript = `#!/bin/sh\n# RepoGuard AI Pre-commit Hook\nrepoguard-ai scan .\nif [ $? -ne 0 ]; then\n  echo "Commit blocked by RepoGuard AI. Fix security issues first."\n  exit 1\nfi\n`;
      fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
      console.log(pc.green("✅ Pre-commit hook installed successfully at .git/hooks/pre-commit"));
    } catch (e: any) {
      console.error(pc.red(`Failed to install hook. Make sure this is a git repository. Error: ${e.message}`));
    }
  });

program
  .command("plant-canary")
  .description("Generates a fake .env honeypot to detect silent intrusions")
  .action(() => {
    try {
      const canaryPath = path.join(process.cwd(), ".env.canary");
      // As chaves abaixo são estruturalmente idênticas às reais, mas inofensivas.
      // Em uma integração real, elas fariam ping em um servidor Thinkst Canary.
      const canaryContent = `# DON'T EDIT - AUTO-GENERATED BY REPOGUARD AI
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
GITHUB_TOKEN=ghp_k7mD3ngBpxRfiCyExampleTokenForCanary`;
      
      fs.writeFileSync(canaryPath, canaryContent, { mode: 0o600 });
      console.log(pc.green(`🍯 Honeypot planted successfully at ${canaryPath}`));
      console.log(pc.yellow(`If a hacker accesses your machine and attempts to use these keys, they will fail and the intrusion can be audited.`));
    } catch (e: any) {
      console.error(pc.red(`Failed to plant canary. Error: ${e.message}`));
    }
  });

program
  .command("scan")
  .description("Scan a directory for security risks")
  .argument("<path>", "Path to the directory to scan")
  .option("--json", "Output report in JSON format")
  .option("--sarif", "Output report in SARIF format for GitHub Advanced Security")
  .option("-c, --config <path>", "Path to custom config file (YAML)")
  .option("--fail-on <severity>", "Fail with exit code 1 if risk score meets or exceeds this severity (LOW, MEDIUM, HIGH, CRITICAL)")
  .option("--auto-fix", "Automatically fix determinable security issues (e.g., removing secrets or upgrading insecure functions)")
  .action(async (targetPath: string, options: { json?: boolean; sarif?: boolean; config?: string; failOn?: string; autoFix?: boolean }) => {
    try {
      const config = loadConfig(options.config);
      
      if (options.failOn) {
        const severities = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
        if (severities.includes(options.failOn.toUpperCase())) {
          if (!config.severity) config.severity = {};
          config.severity.failOn = options.failOn.toUpperCase() as Severity;
        } else {
          console.error(pc.red(`Invalid severity for --fail-on: ${options.failOn}`));
          process.exit(1);
        }
      }

      const rules = getEnabledRules(config);
      const scanner = new Scanner(config, rules);

      let { filesScanned, findings } = await scanner.scan(targetPath);
      
      let fixedCount = 0;
      if (options.autoFix) {
        const fixableFindings = findings.filter(f => f.autoFix);
        if (fixableFindings.length > 0) {
          console.log(pc.cyan(`\n🛠️  Auto-Fix is enabled. Applying fixes to ${fixableFindings.length} issues...`));
          
          for (const finding of fixableFindings) {
            try {
              const fileContent = fs.readFileSync(finding.filePath, "utf-8");
              // Usamos split.join para funcionar como replaceAll
              const newContent = fileContent.split(finding.autoFix!.searchValue as string).join(finding.autoFix!.replaceValue);
              
              if (fileContent !== newContent) {
                fs.writeFileSync(finding.filePath, newContent, "utf-8");
                fixedCount++;
                console.log(pc.green(`   ✅ Fixed ${finding.ruleId} in ${finding.filePath}`));
              }
            } catch (e: any) {
              console.error(pc.yellow(`   ⚠️ Failed to auto-fix ${finding.filePath}: ${e.message}`));
            }
          }
          
          // Removemos os findings corrigidos do relatório final
          findings = findings.filter(f => !f.autoFix);
        }
      }

      const riskScore = calculateRiskScore(findings);

      if (options.sarif) {
        printSarifReport(findings);
      } else if (options.json) {
        printJsonReport(findings, filesScanned, riskScore);
      } else {
        printTerminalReport(findings, filesScanned, riskScore);
      }

      if (options.autoFix && fixedCount > 0) {
         console.log(pc.green(`\n✨ Successfully auto-fixed ${fixedCount} security vulnerabilities!`));
      }

      const severities = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
      const failOnScore = config.severity?.failOn || "HIGH";
      const currentScoreIndex = severities.indexOf(riskScore);
      const failOnScoreIndex = severities.indexOf(failOnScore);

      if (findings.length > 0 && currentScoreIndex >= failOnScoreIndex) {
        if (!options.json) {
          console.error(pc.red(`\nScan failed. Remaining risk score ${riskScore} meets or exceeds the failOn threshold of ${failOnScore}.`));
        }
        process.exit(1);
      } else {
        process.exit(0);
      }

    } catch (error: any) {
      console.error(pc.red(`Error during scan: ${error.message}`));
      process.exit(1);
    }
  });

program.parse();
