name: 'Security Scan (RepoGuard AI)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  repoguard:
    name: Run RepoGuard AI Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Scan Repository
        uses: ./
        with:
          fail-on: HIGH
          format: terminal
